examples:
  rails:
  - default_image: Default
  - rounded_image: Rounded
  - custom_error_image: Error Handling
  react:
  - default_image: Default
  - rounded_image: Rounded
  - custom_error_image: Error Handling
